### ISSUE TITLE
Memory access out of bounds

### ISSUE THREAD

**Issue by gparmeggiani** [likec4/likec4#1148]
Hello! Latest version (1.14.0) reports this error:

![image](https://github.com/user-attachments/assets/c50dc2dc-44a7-4d2f-9262-a4adba7c4371)

How to debug this? Is there a way to obfuscate the model and send it to you for analysis?

**Comment by davydkov** [comment]
Hey @gparmeggiani,

There are some heuristics to optimize the layout, but unfortunately, these sometimes lead to errors with the WASM version.
I assume you don’t encounter this issue with the Graphviz binary version, correct?

To debug this, I indeed need your model, but there isn’t an automated way to obfuscate it.

**Comment by gparmeggiani** [comment]
yes, using graphviz solves the issue for me. 
At this point I can't promise I'll manually obfuscate the model for further debugging, as it is quite big. ...maybe a future feature of likec4?

**Comment by jentor** [comment]
Hi @davydkov!

Also got this error `memory access out of bounds` for not-so-big model in ci.
Tried to make it work with `--use-dot`, but with unluck.

Could you please help with this error?

Here is my new error:
```
[vite-plugin-likec4] Could not load likec4-plugin/dot-sources.js (imported by usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/-view-lazy-data-WZmbIsHq.js): Command was killed with SIGSEGV (Segmentation fault): dot -Tsvg -y

Warning: cell size too small for content
Warning: cell size too small for content
in label of node developer
    at $Q (file:///usr/local/lib/node_modules/likec4/dist/shared/likec4.BkLj38-D.mjs:1781:8211)
    at g0 (file:///usr/local/lib/node_modules/likec4/dist/shared/likec4.BkLj38-D.mjs:1807:1340)
    at Toe (file:///usr/local/lib/node_modules/likec4/dist/shared/likec4.BkLj38-D.mjs:1814:36518)
    at Doe (file:///usr/local/lib/node_modules/likec4/dist/shared/likec4.BkLj38-D.mjs:1814:36238)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///usr/local/lib/node_modules/likec4/dist/shared/likec4.BkLj38-D.mjs:1819:654 {
  shortMessage: 'Command was killed with SIGSEGV (Segmentation fault): dot -Tsvg -y',
  command: 'dot -Tsvg -y',
  escapedCommand: 'dot -Tsvg -y',
  cwd: '/',
  durationMs: 13.197044,
  failed: true,
  timedOut: false,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: true,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  signal: 'SIGSEGV',
  signalDescription: 'Segmentation fault',
  stdout: '',
  stderr: 'Warning: cell size too small for content\n' +
    'Warning: cell size too small for content\n' +
    'in label of node developer\n' +
    'Warning: cell size too small for content\n' +
    'Warning: cell size too small for content\n' +
    'in label of node ...\n' +
    'Warning: cell size too small for content\n' +
    'Warning: cell size too small for content\n' +
    'in label of node ...\n' +
    'Warning: cell size too small for content\n' +
    'Warning: cell size too small for content\n' +
    'in label of node ...\n' +
    'Warning: cell size too small for content\n' +
    'Warning: cell size too small for content\n' +
    'in label of node ...',
  ipcOutput: [],
  pipedFrom: [],
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-likec4',
  hook: 'load',
  watchFiles: [
    '/usr/local/lib/node_modules/likec4/dist/__app__/index.html',
    'favicon.svg',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/main.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/style.css',
    '/usr/local/lib/node_modules/likec4/node_modules/react/jsx-runtime.js',
    '/usr/local/lib/node_modules/likec4/node_modules/react-dom/client.js',
    '/usr/local/lib/node_modules/likec4/node_modules/react/index.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/main-E2hyQKFO.js',
    '/usr/local/lib/node_modules/likec4/node_modules/react/cjs/react.production.min.js',
    '/usr/local/lib/node_modules/likec4/node_modules/react/cjs/react-jsx-runtime.production.min.js',
    '/usr/local/lib/node_modules/likec4/node_modules/react-dom/index.js',
    '/usr/local/lib/node_modules/likec4/node_modules/react-dom/cjs/react-dom.production.min.js',
    '/usr/local/lib/node_modules/likec4/node_modules/scheduler/index.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/tanstack-router-CF1kJvtP.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/const.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/icons.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/-index-overview-DrCqsLHx.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/index-CIsxIzOH.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/-view-lazy-data-WZmbIsHq.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/likec4-DF_Jsv_p.js',
    '/usr/local/lib/node_modules/likec4/dist/__app__/src/chunks/mantine-BzD51ZKm.js',
    '/usr/local/lib/node_modules/likec4/node_modules/scheduler/cjs/scheduler.production.min.js',
    '/usr/local/lib/node_modules/likec4/react/index.mjs',
    '/usr/local/lib/node_modules/likec4/icons/gcp/cloud-gpu.js',
    '/usr/local/lib/node_modules/likec4/icons/gcp/filestore.js',
    '/usr/local/lib/node_modules/likec4/icons/gcp/google-kubernetes-engine.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/adobe-illustrator.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/airflow.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/arduino.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/elasticsearch.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/fast-api.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/gitlab.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/google-cloud.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/graphql.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/jira.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/kafka.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/kubernetes.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/open-api.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/postgresql.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/python.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/reach.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/redis.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/swift.js',
    '/usr/local/lib/node_modules/likec4/icons/tech/the-algorithms.js'
  ]
}
```

Dockerfile
```
FROM node:alpine AS build
RUN apk add graphviz 
RUN npm install --global likec4
COPY ./arch-model /source/
RUN likec4 build --use-dot --use-hash-history -o /dist /source
```

**Comment by nrogoff** [comment]
I am also getting this error when I run `npx likec4 build -o ./dist` from the VS code terminal.

```
15:32:14 c4:lib INFO generating virtual:likec4/icons

 ERROR  FAILED GraphvizWasmAdapter: dot                                                                                                                                                         graphviz-wasm
digraph {

...
...


memory access out of bounds

    at c.layout (/C:/Users/nicholas.rogoff/AppData/Local/npm-cache/_npx/f8ded909d942c3b7/node_modules/@hpcc-js/wasm-graphviz/dist/index.js:3:623)
    at /C:/Users/nicholas.rogoff/AppData/Local/npm-cache/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.D7BM0ZAO.mjs:222:40
    at async /C:/Users/nicholas.rogoff/AppData/Local/npm-cache/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.D7BM0ZAO.mjs:219:624


 WARN  Retrying...                                                                                                                                                                              graphviz-wasm  

transforming (5) ..\icons\azure\application-insights.js
 ERROR  FAILED GraphvizWasmAdapter: dot                                                                                                                                                         graphviz-wasm  
digraph {

...
...

 memory access out of bounds

    at c.layout (/C:/Users/nicholas.rogoff/AppData/Local/npm-cache/_npx/f8ded909d942c3b7/node_modules/@hpcc-js/wasm-graphviz/dist/index.js:3:623)
    at /C:/Users/nicholas.rogoff/AppData/Local/npm-cache/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.D7BM0ZAO.mjs:222:40
    at async /C:/Users/nicholas.rogoff/AppData/Local/npm-cache/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.D7BM0ZAO.mjs:219:624


 WARN  Retrying...                                                                                                                                                                              graphviz-wasm  

15:32:18 c4:lib INFO ✓ 51 modules transformed.
15:32:27 c4:lib INFO ../../../../../../../../../NICHOL~1.ROG/AppData/Local/Temp/.likec4-public-IbnqVu/likec4-views.js  3,078.79 kB │ gzip: 785.46 kB
15:32:27 c4:lib INFO ✓ built in 17.24s
15:32:27 c4:build INFO vite v5.4.11 building for production...
transforming (29) src\chunks\main-CtzxB_vG.js15:32:28 c4:build INFO generating virtual:likec4/model
15:32:28 c4:build INFO generating virtual:likec4/previews

```

And then it just sits there for ever until I kill it.

However I can run `npx likec4 start` and get a similar error, but it then completes the build successfully and the local app seems to work...eventually!

**Comment by kieronlanning** [comment]
I've recently started to experience this too - has anyone found a workaround?

**Comment by davydkov** [comment]
I've just was told interesting fact.
Guys had issues with wasm and binary graphviz on ubuntu, but no issues with self-compiled graphviz 12.2.1, also they reported no issues with latest graphviz on alpine.
As a recipe they shared this Dockerfile (so basically they start likec4 cli in docker):

```Dockerfile
# Stage 1: Build Graphviz
FROM ubuntu:22.04 AS builder

# Install build dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libexpat1-dev \
    libgd-dev \
    libpango1.0-dev \
    libgts-dev \
    libcairo2-dev \
    libglib2.0-dev \
    libgtk2.0-dev \
    libgtkglext1-dev \
    libglade2-dev \
    libtool \
    libltdl-dev \
    libperl-dev \
    pkg-config \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Download and extract Graphviz source
WORKDIR /tmp
RUN wget https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/12.2.1/graphviz-12.2.1.tar.gz \
    && tar -xzf graphviz-12.2.1.tar.gz

# Build and install Graphviz
WORKDIR /tmp/graphviz-12.2.1
RUN ./configure \
    && make \
    && make install DESTDIR=/install \
    && ldconfig

# Stage 2: Create slim image with Graphviz
FROM ubuntu:22.04

# Copy Graphviz binaries and libraries from builder
COPY --from=builder /install /


ENV DEBIAN_FRONTEND=noninteractive


# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    libexpat1 \
    libgd3 \
    libpango-1.0-0 \
    libpangocairo-1.0-0 \
    libcairo2 \
    libglib2.0-0 \
    libltdl7 \
    libpango-1.0-0 \
    libgts-bin \
    libgtk2.0-bin \
    curl \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# Set up environment
ENV LD_LIBRARY_PATH=/usr/local/lib

# Install Node.js 20.x
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*


# Set the working directory in the container
VOLUME /app
WORKDIR /app

RUN mkdir /build
VOLUME [ "/build" ]

# Install LikeC4 CLI globally
RUN npm install -g likec4

# Verify installation
RUN dot -V
RUN dot -c


EXPOSE 5173
```
