### ISSUE TITLE
Error when using autoLayout BottomTop or TopBottom 

### ISSUE THREAD

**Issue by mielvds** [likec4/likec4#1218]
While `autoLayout LeftRight` works, using `TopBottom` or `BottomTop` results in the following error:

```
10:55:28 AM c4:vite INFO trigger hmr likec4-plugin/icons.js
10:55:28 AM c4:vite INFO hmr update /@id/__x00__likec4-plugin/icons.js
10:55:28 AM c4:vite INFO trigger hmr likec4-plugin/previews.js
10:55:28 AM c4:vite INFO hmr update /@id/__x00__likec4-plugin/previews.js
10:55:28 AM c4:vite INFO trigger hmr likec4-plugin/model.js
10:55:28 AM c4:vite INFO hmr update /@id/__x00__likec4-plugin/model.js
10:55:28 AM c4:vite INFO generating virtual:likec4/icons
10:55:28 AM c4:vite INFO generating virtual:likec4/previews
10:55:28 AM c4:vite INFO generating virtual:likec4/model
lib/pathplan//home/runner/work/hpcc-js-wasm/hpcc-js-wasm/vcpkg/buildtrees/graphviz/src/12.1.2-1c6246ab35.clean/lib/pathplan/shortest.c:334: triangulation failed
lib/pathplan//home/runner/work/hpcc-js-wasm/hpcc-js-wasm/vcpkg/buildtrees/graphviz/src/12.1.2-1c6246ab35.clean/lib/pathplan/shortest.c:183: source point not in any triangle

 ERROR  failed on parsing view containers edge dissemination_platform.iiif_image_etl:dissemination_platform.iiif_image_api _draw_:                                                                                                                                                      
undefined

10:55:28 AM c4:lsp  ERROR TypeError: Cannot read properties of undefined (reading 'filter')
    at Vx (file:///Users/mielvandersande/.npm/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.DLr42w54.mjs:1762:193)
    at UJ (file:///Users/mielvandersande/.npm/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.DLr42w54.mjs:1765:105)
    at Kx (file:///Users/mielvandersande/.npm/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.DLr42w54.mjs:1765:789)
    at WJ.layout (file:///Users/mielvandersande/.npm/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.DLr42w54.mjs:1765:3809)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async file:///Users/mielvandersande/.npm/_npx/f8ded909d942c3b7/node_modules/likec4/dist/shared/likec4.DLr42w54.mjs:1819:10597
```

**Comment by davydkov** [comment]
Hey @mielvds 

Thank you for reporting.
Can you provide minimal model to reproduce? Like, obfuscated, and with the elements on this view?

**Comment by mielvds** [comment]
Oddly enough, I can't reproduce it any longer. I suppose there used to be a problemnatic edge that is no longer there...
