### ISSUE TITLE
Error: No file system is available - whilst using browser based github.dev

### ISSUE THREAD

**Issue by simonwfarrow** [likec4/likec4#1343]
Hi,

As per title I see the following error (many times) when using github.dev on a custom repo.

```
language-server-worker.js:163 Uncaught (in promise) Error: No file system is available.
    at Lx.readFile (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:7305)
    at ap.update (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:154:6073)
    at https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:13886
    at _p.runCancelable (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:14823)
    at async _p.buildDocuments (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:13816)
    at async _p.update (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:13114)
    at async https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:18895
    at async Promise.all (index 0)
    at async Np.performNextOperation (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.17.1/extension/dist/browser/language-server-worker.js:163:18810)
```

followed by:

```
Attempted reference resolution before document reached ComputedScopes state (vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a342c226964223a2265636f6d227d7d/wp-access-for-ecomm-pilot/mdl/src/projects/simplification/identity/identity.c4).
createLinkingError @ language-server-worker.js:154
getCandidate @ language-server-worker.js:154
getLinkedNode @ language-server-worker.js:154
get ref @ language-server-worker.js:154
(anonymous) @ language-server-worker.js:193
(anonymous) @ language-server-worker.js:193
iterator @ language-server-worker.js:40
find @ language-server-worker.js:40
getElement @ language-server-worker.js:154
getCandidate @ language-server-worker.js:154
doLink @ language-server-worker.js:154
(anonymous) @ language-server-worker.js:154
forEach @ language-server-worker.js:40
link @ language-server-worker.js:154
await in link
(anonymous) @ language-server-worker.js:163
runCancelable @ language-server-worker.js:163
await in runCancelable
buildDocuments @ language-server-worker.js:163
```

**Comment by simonwfarrow** [comment]
I tried with vscode.dev and got similar behaviour but some extra error messages:

```
language-server-worker.js:175 lsp:debug [ModelBuilder] No documents to build model from
console.ts:137 [Extension Host] debug [LikeC4Model.fetchComputedModel] 424ms
log.ts:445   ERR [Extension Host] %cerror 
      background: #c0392b;
      border-radius: 0.5em;
      color: white;
      font-weight: bold;
      padding: 2px 0.5em;
     SyntaxError: Failed to execute 'measure' on 'Performance': The mark 'fetchComputedModel:start' does not exist.
	at Vy.fetchModelAndUpdateCaches (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:1635:3979)
	at async Vy.fetchComputedModel (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:1635:3805)
	at async Object.eval [as handler] (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:1652:1498)
	at async lN.processRequestMessage (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:65:26354)
	at async lN.processMessage (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:65:24310)
console.ts:137 [Extension Host] error SyntaxError: Failed to execute 'measure' on 'Performance': The mark 'fetchComputedModel:start' does not exist.
	at Vy.fetchModelAndUpdateCaches (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:1635:3979)
	at async Vy.fetchComputedModel (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:1635:3805)
	at async Object.eval [as handler] (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:1652:1498)
	at async lN.processRequestMessage (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:65:26354)
	at async lN.processMessage (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.18.0/extension/dist/browser/extension.js#vscode-extension:65:24310)
YJi @ console.ts:137
```
![Screenshot 2024-12-13 at 17 11 34](https://github.com/user-attachments/assets/0308bad2-745f-4a4c-9401-9a6ce79a9252)

**Comment by davydkov** [comment]
Hey @simonwfarrow 

Could you please verify if problem still exists in `1.19` ?
And share the output of extension (up to the next line after `LanguageClient started`)
In my case 
```
2025-01-01 16:17:10.982 [info] active browser extension
2025-01-01 16:17:10.982 [info] Workspace: vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a352c226964223a226d61696e227d7d/likec4/example-cloud-system
2025-01-01 16:17:10.982 [info] Activate in 1 workspace folders
  example-cloud-system: vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a352c226964223a226d61696e227d7d/likec4/example-cloud-system
2025-01-01 16:17:10.982 [info] Starting LanguageClient...
2025-01-01 16:17:11.167 [info] [Debug - 4:17:11 PM] [lsp] registerValidationChecks
2025-01-01 16:17:11.168 [info] [Debug - 4:17:11 PM] [lsp] [FqnIndex] Created
2025-01-01 16:17:11.183 [info] [Debug - 4:17:11 PM] [lsp] [ModelBuilder] Created
2025-01-01 16:17:11.185 [info] [Info  - 4:17:11 PM] [lsp] [ServerRpc] init
2025-01-01 16:17:11.257 [info] LanguageClient started
2025-01-01 16:17:11.258 [info] recursiveSearchSources
```

**Comment by simonwfarrow** [comment]
Sorry for the delay, long holiday 😄 

The performance markers errors appeared to have gone.

But the build is still failing, lots of warnings and then an error about the file system again (below).

Its a large model, a much smaller simpler one seems to work ok.

```
[Extension Host] info [InitWorkspace] Send request buildDocuments
language-server-worker.js:182 lsp:debug [ServerRpc] received request to build:
  changed (total 336):
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/worldpay.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/product_repo.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/terminals_org.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/domains/integration_domain.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/domains/orchestration_domain.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/devX_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/ecommIntegration_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/estateMgmnt_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/tranRouting_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/products/gateway/gateway_product.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/products/gateway/features/partiesApi_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/products/gateway/features/paymentsApi_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/products/gateway/features/payoutsApi_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/products/gateway/features/routingService_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranRouting/products/gateway/features/splitPaymentsAPI_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranOrchestration/tranOrchestration_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranOrchestration/products/authentication/requestAuthentication_product.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranOrchestration/products/authentication/features/jwtService_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/terminals/capabilities/tranOrchestration/products/authentication/features/tokenAuthService_feature.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/servicing/servicing_org.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/servicing/domains/salesServicing_domain.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/servicing/capabilities/acquisition_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b2274797065223a362c226964223a226d61696e227d7d/wp-access-for-ecomm-pilot/mdl/v2/product/organizations/servicing/capabilities/partnerMgmnt_cap.c4
    - vscode-vfs://github%2B7b2276223a312c22726566223a7b
35language-server-worker.js:182 lsp:debug [ModelBuilder] No documents to build model from
language-server-worker.js:182 lsp:debug [ModelBuilder] No documents to build model from (repeated 2 times)
14language-server-worker.js:182 lsp:debug [ModelBuilder] No documents to build model from
console.ts:137 [Extension Host] warn Error: Request likec4/build failed with message: No file system is available.
	at D (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.19.2/extension/dist/browser/extension.js#vscode-extension:8:231)
	at dt (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.19.2/extension/dist/browser/extension.js#vscode-extension:7:6239)
	at At (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.19.2/extension/dist/browser/extension.js#vscode-extension:7:6363)
	at eval (https://likec4.vscode-unpkg.net/likec4/likec4-vscode/1.19.2/extension/dist/browser/extension.js#vscode-extension:7:6127)
eXi @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
B @ event.ts:1243
fire @ event.ts:1274
D.o.onmessage @ webWorkerExtensionHost.ts:230Understand this warningAI
console.ts:137 [Extension Host] info Extension activated
644.357904918e6f9d8132a5.js:1 vscs:web-client:fbf9:workbench-telemetry:telemetry-service track codespaces/webeditor/connection/action_stop
26037 log entries are not shown.Understand this warningAI
26037 log entries are not shown.Understand this warningAI
26036 log entries are not shown.
```
