### ISSUE TITLE
Failed attempt to layout with graphviz

### ISSUE THREAD

**Issue by gparmeggiani** [likec4/likec4#614]
I stumbled upon this error (version 0.57.1): 

```
Failed attempt to layout with graphviz: InvariantError: edge should have only one bezier draw op
    at invariant (file:///usr/lib/node_modules/likec4/dist/cli/index.js:28:62922)
    at parseEdgePoints (file:///usr/lib/node_modules/likec4/dist/cli/index.js:222:9308)
    at parseGraphvizJson (file:///usr/lib/node_modules/likec4/dist/cli/index.js:225:660)
    at dotLayoutFn (file:///usr/lib/node_modules/likec4/dist/cli/index.js:223:737)
    at bD.attempt (file:///usr/lib/node_modules/likec4/dist/cli/index.js:230:691073)
    at async file:///usr/lib/node_modules/likec4/dist/cli/index.js:230:690883
failed on parsing edge _draw_:
[
  {
    "op": "S",
    "style": "setlinewidth(2)"
  },
  {
    "op": "S",
    "style": "dashed"
  },
  {
    "op": "c",
    "grad": "none",
    "color": "#6e6e6e"
  },
  {
    "op": "b",
    "points": [
      [
        1024.07,
        855.56
      ],
      [
        1008.82,
        857.12
      ],
      [
        993.57,
        858.45
      ],
      [
        978.88,
        859.4
      ],
      [
        920.44,
        863.17
      ],
      [
        905.56,
        863.17
      ],
      [
        847.12,
        859.4
      ],
      [
        836.56,
        858.72
      ],
      [
        825.71,
        857.84
      ],
      [
        814.78,
        856.82
      ]
    ]
  },
  {
    "op": "S",
    "style": "dashed"
  },
  {
    "op": "c",
    "grad": "none",
    "color": "#6e6e6e"
  },
  {
    "op": "b",
    "points": [
      [
        1024.05,
        832.8
      ],
      [
        958.16,
        832.8
      ],
      [
        881.69,
        832.8
      ],
      [
        814.55,
        832.8
      ]
    ]
  }
]
Failed attempt to layout with graphviz: InvariantError: edge should have only one bezier draw op
    at invariant (file:///usr/lib/node_modules/likec4/dist/cli/index.js:28:62922)
    at parseEdgePoints (file:///usr/lib/node_modules/likec4/dist/cli/index.js:222:9308)
    at parseGraphvizJson (file:///usr/lib/node_modules/likec4/dist/cli/index.js:225:660)
    at dotLayoutFn (file:///usr/lib/node_modules/likec4/dist/cli/index.js:223:737)
    at bD.attempt (file:///usr/lib/node_modules/likec4/dist/cli/index.js:230:691073)
    at async file:///usr/lib/node_modules/likec4/dist/cli/index.js:230:690937
3:42:11 PM c4:lsp  ERROR Error: Failed to layout with graphviz
    at file:///usr/lib/node_modules/likec4/dist/cli/index.js:230:690977

```

**Comment by davydkov** [comment]
I just added this check, but I never really thought it would actually happen!
I investigate options. 
Could you please share your model to reproduce? (obfuscated is also good)

**Comment by gparmeggiani** [comment]
I sent you an email with the model
