### ISSUE TITLE
Vite error on build with v1.6.0

### ISSUE THREAD

**Issue by simonwfarrow** [likec4/likec4#860]
Hi,

I just upgraded to v1.6.0 to make use of the embedded icons and get this error whilst running the build command:

```
ERROR  node_modules/likec4/icons/aws/lambda.js (1:22): "jsxs" is not exported by "__vite-optional-peer-dep:react/jsx-runtime:likec4", imported by "node_modules/likec4/icons/aws/lambda.js".
file: /Users/e5591703/Projects/mdl/node_modules/likec4/icons/aws/lambda.js:1:22

1: import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
                         ^
2: /**
3:  * @component


  file: node_modules/likec4/icons/aws/lambda.js:1:22
  
  1: import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
  ^
  2: /**
  3:  * @component
  
  at getRollupError (node_modules/rollup/dist/es/shared/parseAst.js:396:41)
  at error (node_modules/rollup/dist/es/shared/parseAst.js:392:42)
  at Module.error (node_modules/rollup/dist/es/shared/node-entry.js:13858:16)
  at Module.traceVariable (node_modules/rollup/dist/es/shared/node-entry.js:14306:29)
  at ModuleScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:11984:39)
  at ReturnValueScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
  at FunctionBodyScope.findVariable (node_modules/rollup/dist/es/shared/node-entry.js:7432:38)
  at Identifier.bind (node_modules/rollup/dist/es/shared/node-entry.js:6908:40)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:4775:23)
  at CallExpression.bind (node_modules/rollup/dist/es/shared/node-entry.js:9135:15)
```

**Comment by simonwfarrow** [comment]
I wonder if its related to this  and needing to add the icons package to the vite config: https://stackoverflow.com/questions/67068355/error-jsxs-is-not-exported-by-node-modules-react-jsx-runtime-js-on-building-p

**Comment by davydkov** [comment]
Thanks for reporting, I check it ASAP

**Comment by simonwfarrow** [comment]
Thanks for the quick fix !
